---
title: "운행데이터_EDA"

author: "노윤지"
date: "2023-04-10"
output: html_document
---

```{r env, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warnings= FALSE)
library(tidyverse)
library(knitr)
library(gtsummary)
library(labelled)
library(summarytools)
library(kableExtra)
library(magrittr)
library(pander)
```

```{r,warning = FALSE, message = FALSE}
source("retension.R")
```

###  **[Table 1.1] Summary of rider characteristics** 
```{r, warning=FALSE, message=FALSE}
theme_gtsummary_compact()
data_final$group_by_deliver <- data_final$group_by_deliver %>% factor(levels = c("한건", "하위50%","상위10%상위50%","상위10%"))
data_final$group_by_date <- data_final$group_by_date %>% factor(levels = c("하루", "하위50%","상위10%상위50%","상위10%"))
data_final$outcome <- data_final$outcome %>% factor(levels = c(0,1), labels= c("잔존", "이탈"))

print(dfSummary(data_final, plain.ascii = FALSE, style = "multiline", graph.magnif = 0.75, varnumbers=FALSE, valid.col = TRUE, display.labels=TRUE,
                headings=FALSE), method = 'render')

```

###  **[Table 1.2] **descriptive statistics of rider characteristics {.tabset}
#### **[수행건수 비율에 맞춰 그룹화]**
```{r, warning=FALSE, message=FALSE}
data_final %>% 
  tbl_summary(by = group_by_deliver,
              type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ c("{mean} ({sd})", "{min}, {max}"),
              missing_text = "(Missing value)", 
              digits = list(all_continuous() ~ c(1, 2), 
                            all_categorical() ~ c(0, 1))) %>%
  add_overall() %>%
  add_p(pvalue_fun = ~style_pvalue(., digits = 3)) %>%
bold_labels()

```

#### **[실제수행기간 비율에 맞춰 그룹화]**
```{r, warning=FALSE, message=FALSE}
data_final %>% 
  tbl_summary(by = group_by_date,
              type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ c("{mean} ({sd})", "{min}, {max}"),
              missing_text = "(Missing value)", 
              digits = list(all_continuous() ~ c(1, 2), 
                            all_categorical() ~ c(0, 1))) %>%
  add_overall() %>%
  add_p(pvalue_fun = ~style_pvalue(., digits = 3)) %>%
bold_labels()

```

###  **[Table 1.3] **descriptive statistics of rider characteristics {.tabset}
#### **[이탈 그룹 vs 잔존그룹]**
```{r, warning=FALSE, message=FALSE}
data_final %>% 
  tbl_summary(by = outcome,
              type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ c("{mean} ({sd})", "{min}, {max}"),
              missing_text = "(Missing value)", 
              digits = list(all_continuous() ~ c(1, 2), 
                            all_categorical() ~ c(0, 1))) %>%
  add_overall() %>%
  add_p(pvalue_fun = ~style_pvalue(., digits = 3)) %>%
bold_labels()

```

#### **[상위10%상위50%]**
```{r, warning=FALSE, message=FALSE}

data_up50 <- data_final %>% 
  filter(group_by_deliver == '상위10%상위50%' & group_by_date == '상위10%상위50%')

data_up50 %>% 
  tbl_summary(by = outcome,
              type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ c("{mean} ({sd})", "{min}, {max}"),
              missing_text = "(Missing value)", 
              digits = list(all_continuous() ~ c(1, 2), 
                            all_categorical() ~ c(0, 1))) %>%
  add_overall() %>%
  add_p(pvalue_fun = ~style_pvalue(., digits = 3)) %>%
bold_labels()

```

#### **[상위10%]**
```{r, warning=FALSE, message=FALSE}
data_up10 <- data_final %>% 
  filter(group_by_deliver == '상위10%' & group_by_date == '상위10%')

data_up10 %>% 
  tbl_summary(by = outcome,
              type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ c("{mean} ({sd})", "{min}, {max}"),
              missing_text = "(Missing value)", 
              digits = list(all_continuous() ~ c(1, 2), 
                            all_categorical() ~ c(0, 1))) %>%
  add_overall() %>%
  add_p(pvalue_fun = ~style_pvalue(., digits = 3)) %>%
bold_labels()

```


