---
title: "Risk Ratio"

author: "노윤지"
date: "2023-04-24"
output: html_document
---

```{r env, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warnings= FALSE)
library(tidyverse)
library(knitr)
library(gtsummary)
library(labelled)
library(summarytools)
library(kableExtra)
library(magrittr)
library(pander)
```

```{r,warning = FALSE, message = FALSE}
#source("make_churn.R")
source("90day-180day.R")
```

###  **[Table 1.1] Summary of rider characteristics** 
```{r, warning=FALSE, message=FALSE}
theme_gtsummary_compact()
data <- data_180[c("ratio_group_90", "ratio_group")] %>% 
  filter(!is.na(ratio_group_90))

data %>% tbl_summary(by = "ratio_group")


# data_mark$ratio_group <- data_mark$ratio_group %>% 
#   factor(levels = c("zero","one","two","three","four","five","six","seven","eight","nine"), 
#          labels = c("zero","one","two","three","four","five","six","seven","eight","nine"))
# 
# print(dfSummary(data_mark, plain.ascii = FALSE, style = "multiline", graph.magnif = 0.75, varnumbers=FALSE, valid.col = TRUE, display.labels=TRUE,
#                 headings=FALSE), method = 'render')

```
###  **[Table 1.2] **descriptive statistics of rider characteristics {.tabset}
#### **[ratio_group]**
```{r, warning=FALSE, message=FALSE}
data_mark %>%
 # group_by(rgn1_1st, method) %>% 
  tbl_summary(by = "ratio_group",
              type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ c("{mean} ({sd})", "{min}, {max}"),
              missing_text = "(Missing value)", 
              digits = list(all_continuous() ~ c(1, 2), 
                            all_categorical() ~ c(0, 1))) %>%
  add_overall() %>%
  add_p(pvalue_fun = ~style_pvalue(., digits = 3)) %>%
bold_labels()
```

#### **[method]**
```{r, warning=FALSE, message=FALSE}
data_mark[c("method","churn","ratio_group")] %>%
  group_by(method,churn) %>% 
  tbl_summary(by = "method",
              type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ c("{mean} ({sd})", "{min}, {max}"),
              missing_text = "(Missing value)", 
              digits = list(all_continuous() ~ c(1, 2), 
                            all_categorical() ~ c(0, 1))) %>%
  add_overall() %>%
  add_p(pvalue_fun = ~style_pvalue(., digits = 3)) %>%
bold_labels()
```

#### **[rgn1]**
```{r, warning=FALSE, message=FALSE}
data_mark %>%
 # group_by(rgn1_1st, method) %>% 
  tbl_summary(by = "rgn1_1st",
              type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ c("{mean} ({sd})", "{min}, {max}"),
              missing_text = "(Missing value)", 
              digits = list(all_continuous() ~ c(1, 2), 
                            all_categorical() ~ c(0, 1))) %>%
  add_overall() %>%
  add_p(pvalue_fun = ~style_pvalue(., digits = 3)) %>%
bold_labels()
```
